name: workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
jobs:
  integration:
    name : Continuous Integration
    runs-on: ubuntu-latest  # Environment to run on
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Lint code
        run: echo "Limiting repository"

      - name: Run unit tests
        run: echo "Running unit Test"
